#ifndef LIBGOMP_H
#define LIBGOMP_H

#include "Compiler.h"

#define GOMP_STACK_SHIFT 10
#define GOMP_STACK_SIZE (2<<GOMP_STACK_SHIFT)

#define GOMP_TID_BITS 2
#define GOMP_NUM_THREADS (1<<GOMP_TID_BITS)

extern char GOMP_STACKS[GOMP_NUM_THREADS][GOMP_STACK_SIZE] ALIGN(GOMP_STACK_SIZE);

#endif // LIBGOMP_H
